europePmcLabsLink:
  - dataPipelineId: europepmc_labslink_data_pipeline_1
    source:
      bigQuery:
        sqlQuery: |-
          SELECT DISTINCT article_doi
          FROM `elife-data-pipeline.de_proto.v_sciety_event` AS event
          WHERE event_name = 'EvaluationRecorded'
              AND article_doi IS NOT NULL
    target:
      ftp:
        host: 'labslink.ebi.ac.uk'
        username: 'elinks'
        parametersFromFile:
          - parameterName: password
            filePathEnvName: EUROPEPMC_LABSLINK_FTP_PASSWORD_FILE_PATH
          - parameterName: directoryName
            filePathEnvName: EUROPEPMC_LABSLINK_FTP_DIRECTORY_NAME_FILE_PATH
