europePmc:
  - dataPipelineId: europepmc_data_pipeline_1
    source:
      # apiUrl: 'https://www.ebi.ac.uk/europepmc/webservices/rest/search'
      apiUrl: 'https://www.ebi.ac.uk/europepmc/webservices/test/rest/search'
      search:
        query: 'DOI:10.1101/2021.07.05.451181 OR DOI:10.1101/2021.08.10.455713'
        hasTextMinedTerms: 'Y'
      extractIndividualResultsFromResponse: False
      maxDays: 1000  # limit the number of days to process from start date
    target:
      projectName: 'elife-data-pipeline'
      datasetName: '{ENV}'
      tableName: test_europepmc_responses_v2
    state:
      initialState:
        startDate: '2020-01-01'
      stateFile:
        bucketName: '{ENV}-elife-data-pipeline'
        objectName: 'airflow-config/europepmc/{ENV}-state.json'
    batchSize: 1
