version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    boto-group:
      patterns:
        - "boto3"
        - "botocore"
    k8s-group:
      patterns:
        - "apache-airflow-providers-cncf-kubernetes"
        - "kubernetes"
