version: '3.4'

x-airflow-env:
  &airflow-env
    - CIVICRM_API_KEY_FILE_PATH=/home/airflow/secrets/civi_api_key
    - CIVICRM_SITE_KEY_FILE_PATH=/home/airflow/secrets/civi_site_key
    - PATH_TO_TOGGL_API_TOKEN_FILE=/home/airflow/secrets/toggl.txt
    - GMAIL_E2E_TEST_ACCOUNT_SECRET_FILE=/home/airflow/secrets/gmail_end2end_test_credentials.json


x-airflow-volumes:
  &airflow-volumes
    - ~/.config/gcloud/application_default_credentials.json:/tmp/credentials.json
    - ./.secrets:/home/airflow/secrets
    - ./dags:/opt/airflow/dags
    - ./data_pipeline:/opt/airflow/data_pipeline
    - ./tests:/opt/airflow/tests

services:
    data-hub-dags-dev:
        volumes: *airflow-volumes
        environment: *airflow-env

    webserver:
        ports:
            - "8080:8080"
        volumes: *airflow-volumes
        environment: *airflow-env

    scheduler:
        volumes: *airflow-volumes
        environment: *airflow-env


    dask-worker:
        volumes: *airflow-volumes
        environment: *airflow-env

    test-client:
        volumes: *airflow-volumes
        environment: *airflow-env
