version: '3.4'


x-airflow-volumes:
  &airflow-volumes
    - ~/.config/gcloud/application_default_credentials.json:/tmp/credentials.json

services:
    webserver:
        ports:
            - "8080:8080"
        volumes: *airflow-volumes

    scheduler:
        volumes: *airflow-volumes


    dask-worker:
        volumes: *airflow-volumes

    test-client:
        volumes: *airflow-volumes
