version: '3'

services:
    datahub-dags:
        build:
            context: .
        image: elifesciences/datahub-dags
        command: ''

    datahub-dags-dev:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                install_dev: y
        image:  elifesciences/datahub-dags-dev
        command: /bin/sh -c exit 0
        entrypoint: []