version: '3'

services:
    webserver:
        ports:
            - "8080:8080"
        volumes:
            - ~/.config/gcloud/application_default_credentials.json:/tmp/credentials.json


    scheduler:
        volumes:
            - ~/.config/gcloud/application_default_credentials.json:/tmp/credentials.json


    dask-worker:
        volumes:
            - ~/.config/gcloud/application_default_credentials.json:/tmp/credentials.json

    test-client:
        volumes:
            - ~/.config/gcloud/application_default_credentials.json:/tmp/credentials.json