relatedArticles:
  - dataPipelineId: related-articles
    source:
      gitRepoUrl: 'https://api.github.com/repos/elifesciences/elife-article-xml/git/trees/master'
      directoryName: 'articles'
    target:
      projectName: 'elife-data-pipeline'
      datasetName: '{ENV}'
      tableName: related_articles
