elifeArticleXml:
  - dataPipelineId: related-articles
    source:
      gitRepoUrl: 'https://api.github.com/repos/elifesciences/elife-article-xml/git/trees/master'
      headers: {'content-type': 'application/json', 'Accept-Charset': 'UTF-8'}
    target:
      projectName: 'elife-data-pipeline'
      datasetName: '{ENV}'
      tableName: related_articles
