twitterAdsApi:
  # - dataPipelineId: twitter_ads_api_campaign_elife_journal
  #   source:
  #     resource: '/11/accounts/18ce53up4ko/campaigns'
  #     secrets:
  #       parametersFromFile:
  #         - parameterName: api_key
  #           filePathEnvName: TWITTER_API_KEY_FILE_PATH
  #         - parameterName: api_secret
  #           filePathEnvName: TWITTER_API_SECRET_FILE_PATH
  #         - parameterName: access_token
  #           filePathEnvName: TWITTER_ACCESS_TOKEN_FILE_PATH
  #         - parameterName: access_token_secret
  #           filePathEnvName: TWITTER_ACCESS_TOKEN_SECRET_FILE_PATH
  #   target:
  #     projectName: 'elife-data-pipeline'
  #     datasetName: '{ENV}'
  #     tableName: twitter_campaign_details_elife_journal

  - dataPipelineId: twitter_ads_api_campaign_reach_elife_journal
    source:
      resource: '/11/stats/accounts/18ce53up4ko/reach/campaigns'
      paramValueFromBigQuery:
        projectName: 'elife-data-pipeline'
        sqlQuery: |-
          SELECT DISTINCT t_data.id
          FROM `elife-data-pipeline.hc_dev.v_latest_twitter_campaign_details_elife_journal`
          JOIN UNNEST(data) AS t_data
          WHERE t_data.id IN ('git3k', 'gwdrg')
      paramNameForBqValue: campaign_ids
      paramNameForStartTime: start_time
      paramNameForEndTime: end_time
      secrets:
        parametersFromFile:
          - parameterName: api_key
            filePathEnvName: TWITTER_API_KEY_FILE_PATH
          - parameterName: api_secret
            filePathEnvName: TWITTER_API_SECRET_FILE_PATH
          - parameterName: access_token
            filePathEnvName: TWITTER_ACCESS_TOKEN_FILE_PATH
          - parameterName: access_token_secret
            filePathEnvName: TWITTER_ACCESS_TOKEN_SECRET_FILE_PATH
    target:
      projectName: 'elife-data-pipeline'
      datasetName: '{ENV}'
      tableName: twitter_campaign_reach_elife_journal

