semanticScholar:
  - dataPipelineId: semantic_scholar_data_pipeline_1
    matrix:  # similar to ci matrix, currently supporting a single variable only
      doi:
        include:
          bigQuery:
            projectName: 'elife-data-pipeline'
            sqlQuery: |-
              SELECT DISTINCT doi
              FROM `elife-data-pipeline.staging.europepmc_biorxiv_medrxiv_responses` AS response
              WHERE doi IS NOT NULL
              LIMIT 3
        exclude:
          bigQuery:
            ignoreNotFound: true
            projectName: 'elife-data-pipeline'
            sqlQueryTemplate: |-
              SELECT externalIds.DOI
              FROM `elife-data-pipeline.{ENV}.test_semantic_scholar_responses_v1` AS response
              WHERE externalIds.DOI IS NOT NULL
    source:
      apiUrl: 'https://api.semanticscholar.org/graph/v1/paper/{doi}'
      params:
        fields: 'externalIds,url,title,abstract,venue,year,referenceCount,citationCount,influentialCitationCount,isOpenAccess,fieldsOfStudy,s2FieldsOfStudy,authors'
    target:
      projectName: 'elife-data-pipeline'
      datasetName: '{ENV}'
      tableName: test_semantic_scholar_responses_v1
    batchSize: 1000
