gcpProjectName: 'elife-data-pipeline'
importedTimestampFieldName: 'imported_timestamp'

# NOTE THAT there is a limit in the number of dimensions and metrics that can be requested
# information about metrics/dimensions to be used can be found here
# https://ga-dev-tools.appspot.com/dimensions-metrics-explorer/

googleAnalyticsPipelines:
  # Schema
  # - pipelineID: <Pipeline ID>
  #   defaultStartDate: <Date using Format YYYY-MM-DD>
  #   endDate: <Date using Format YYYY-MM-DD>
  #   batchDateInterval:
  #     years: <Number of years to process in one batch>
  #     months: <Number of months to process in one batch>
  #     days: <Number of days to process in one batch>
  #   dataset: <dataset name>
  #   table: <table name>
  #   viewId: <view id of the google analytics view from which data is to be extracted>
  #   dimensions: <list of dimensions>
  #   metrics: <list of metrics>
  #   stateFile:
  #     bucketName: <bucket name>
  #     objectName: <object name>
  # Annotations appended to every record created by data pipeline using the config
  # One can use this to differentiate the source data pipeline of a record when several data pipelines
  # write to the same table
  # recordAnnotations:
  #   - recordAnnotationFieldName: <BigQuery compatible field name>
  #     recordAnnotationValue: <value>
  # logResponse: <whether to log the API response for debugging purpose)

  # - pipelineID: 'ga_universal_analytics_data_1'
  #   defaultStartDate: "2014-11-01"
  #   endDate: "2023-06-30"
  #   batchDateInterval:
  #     months: 1
  #   dataset: '{ENV}'
  #   table: 'temp_ga_universal_analytics_data'
  #   viewId: "93573727"  # "Web traffic excluding eLife IP"

  #   dimensions:
  #     - 'ga:date'
  #     - 'ga:pagePath'
  #   metrics:
  #     - 'ga:sessions'
  #     - 'ga:pageviews'
  #     - 'ga:uniquePageviews'
  #   stateFile:
  #     bucketName: '{ENV}-elife-data-pipeline'
  #     objectName: 'airflow-config/ga-universal-analytics/state/by-view-id/93573727/{ENV}-ga_universal_analytics_data_1.json'

  # Dimensions: yearMonth

  - pipelineID: 'ga_universal_analytics_data_by_year_month_for_user_and_session_metrics_1'
    defaultStartDate: "2014-11-01"
    endDate: "2023-06-30"
    batchDateInterval:
      months: 1
    dataset: '{ENV}'
    table: 'temp_ga_universal_analytics_data'
    viewId: "93573727"  # "Web traffic excluding eLife IP"

    dimensions:
      - 'ga:yearMonth'
    metrics:
      - 'ga:users'
      - 'ga:newUsers'
      - 'ga:percentNewSessions'
      - 'ga:sessionsPerUser'
      - 'ga:sessions'
      - 'ga:bounces'
      - 'ga:bounceRate'
      - 'ga:sessionDuration'
      - 'ga:avgSessionDuration'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/ga-universal-analytics/state/by-view-id/93573727/ga_universal_analytics_data_by_year_month_for_user_and_session_metrics_1.json'

  - pipelineID: 'ga_universal_analytics_data_by_year_month_for_page_metrics_1'
    defaultStartDate: "2014-11-01"
    endDate: "2023-06-30"
    batchDateInterval:
      months: 1
    dataset: '{ENV}'
    table: 'temp_ga_universal_analytics_data'
    viewId: "93573727"  # "Web traffic excluding eLife IP"

    dimensions:
      - 'ga:yearMonth'
    metrics:
      - 'ga:entrances'
      - 'ga:entranceRate'
      - 'ga:pageviews'
      - 'ga:pageviewsPerSession'
      - 'ga:uniquePageviews'
      - 'ga:timeOnPage'
      - 'ga:avgTimeOnPage'
      - 'ga:exits'
      - 'ga:exitRate'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/ga-universal-analytics/state/by-view-id/93573727/ga_universal_analytics_data_by_year_month_for_page_metrics_1.json'

  # Dimensions: yearMonth + pagePath

  - pipelineID: 'ga_universal_analytics_data_by_yearmonth_and_path_for_user_metrics_1'
    defaultStartDate: "2014-11-01"
    endDate: "2023-06-30"
    batchDateInterval:
      months: 1
    dataset: '{ENV}'
    table: 'temp_ga_universal_analytics_data'
    viewId: "93573727"  # "Web traffic excluding eLife IP"

    dimensions:
      - 'ga:yearMonth'
      - 'ga:pagePath'
    metrics:
      - 'ga:users'
      - 'ga:newUsers'
      - 'ga:percentNewSessions'
      - 'ga:sessionsPerUser'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/ga-universal-analytics/state/by-view-id/93573727/ga_universal_analytics_data_by_yearmonth_and_path_for_user_metrics_1.json'

  - pipelineID: 'ga_universal_analytics_data_by_yearmonth_and_path_for_session_metrics_1'
    defaultStartDate: "2014-11-01"
    endDate: "2023-06-30"
    batchDateInterval:
      months: 1
    dataset: '{ENV}'
    table: 'temp_ga_universal_analytics_data'
    viewId: "93573727"  # "Web traffic excluding eLife IP"

    dimensions:
      - 'ga:yearMonth'
      - 'ga:pagePath'
    metrics:
      - 'ga:sessions'
      - 'ga:bounces'
      - 'ga:bounceRate'
      - 'ga:sessionDuration'
      - 'ga:avgSessionDuration'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/ga-universal-analytics/state/by-view-id/93573727/ga_universal_analytics_data_by_yearmonth_and_path_for_session_metrics_1.json'

  - pipelineID: 'ga_universal_analytics_data_by_yearmonth_and_path_for_page_metrics_1'
    defaultStartDate: "2014-11-01"
    endDate: "2023-06-30"
    batchDateInterval:
      months: 1
    dataset: '{ENV}'
    table: 'temp_ga_universal_analytics_data'
    viewId: "93573727"  # "Web traffic excluding eLife IP"

    dimensions:
      - 'ga:yearMonth'
      - 'ga:pagePath'
    metrics:
      - 'ga:entrances'
      - 'ga:entranceRate'
      - 'ga:pageviews'
      - 'ga:pageviewsPerSession'
      - 'ga:uniquePageviews'
      - 'ga:timeOnPage'
      - 'ga:avgTimeOnPage'
      - 'ga:exits'
      - 'ga:exitRate'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/ga-universal-analytics/state/by-view-id/93573727/ga_universal_analytics_data_by_yearmonth_and_path_for_page_metrics_1.json'

  # Dimensions: date + pagePath

  - pipelineID: 'ga_universal_analytics_data_by_date_and_path_for_user_metrics_1'
    defaultStartDate: "2014-11-01"
    endDate: "2023-06-30"
    batchDateInterval:
      months: 1
    dataset: '{ENV}'
    table: 'temp_ga_universal_analytics_data'
    viewId: "93573727"  # "Web traffic excluding eLife IP"

    dimensions:
      - 'ga:date'
      - 'ga:pagePath'
    metrics:
      - 'ga:users'
      - 'ga:newUsers'
      - 'ga:percentNewSessions'
      - 'ga:sessionsPerUser'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/ga-universal-analytics/state/by-view-id/93573727/ga_universal_analytics_data_by_date_and_path_for_user_metrics_1.json'

  - pipelineID: 'ga_universal_analytics_data_by_date_and_path_for_session_metrics_1'
    defaultStartDate: "2014-11-01"
    endDate: "2023-06-30"
    batchDateInterval:
      months: 1
    dataset: '{ENV}'
    table: 'temp_ga_universal_analytics_data'
    viewId: "93573727"  # "Web traffic excluding eLife IP"

    dimensions:
      - 'ga:date'
      - 'ga:pagePath'
    metrics:
      - 'ga:sessions'
      - 'ga:bounces'
      - 'ga:bounceRate'
      - 'ga:sessionDuration'
      - 'ga:avgSessionDuration'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/ga-universal-analytics/state/by-view-id/93573727/ga_universal_analytics_data_by_date_and_path_for_session_metrics_1.json'

  - pipelineID: 'ga_universal_analytics_data_by_date_and_path_for_page_metrics_1'
    defaultStartDate: "2014-11-01"
    endDate: "2023-06-30"
    batchDateInterval:
      months: 1
    dataset: '{ENV}'
    table: 'temp_ga_universal_analytics_data'
    viewId: "93573727"  # "Web traffic excluding eLife IP"

    dimensions:
      - 'ga:date'
      - 'ga:pagePath'
    metrics:
      - 'ga:entrances'
      - 'ga:entranceRate'
      - 'ga:pageviews'
      - 'ga:pageviewsPerSession'
      - 'ga:uniquePageviews'
      - 'ga:timeOnPage'
      - 'ga:avgTimeOnPage'
      - 'ga:exits'
      - 'ga:exitRate'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/ga-universal-analytics/state/by-view-id/93573727/ga_universal_analytics_data_by_date_and_path_for_page_metrics_1.json'
