gcpProjectName: 'elife-data-pipeline'
importedTimestampFieldName: 'data_hub_imported_timestamp'

defaultConfig:
  airflow:
    dagParameters:
      # schedule: '@daily'
      tags:
        - 'GA'
        - 'UA'
    taskParameters:
      retries: 1
    #   queue: 'kubernetes'
    #   executor_config:
    #     pod_override:
    #       spec:
    #         containers:
    #           - name: 'base'
    #             resources:
    #               limits:
    #                 memory: 1Gi
    #                 cpu: 1000m
    #               requests:
    #                 memory: 1Gi
    #                 cpu: 100m

googleAnalyticsPipelines:
  - pipelineID: '{ENV}-some-pipeline-id'
    # defaultStartDate: "2014-11-07"
    defaultStartDate: "2014-11-01"
    # endDate: "2014-11-10"
    endDate: "2023-06-30"
    batchDateInterval:
      months: 1
    dataset: '{ENV}'
    table: 'temp_ua_data_v1'
    # view id of the google analytics view from which data is to be extracted
    viewId: "93573727"  # "Web traffic excluding eLife IP"
    # viewId: "82618489"  # "All Web Site Data"
    #viewId: "82626137"
    # NOTE THAT there is a limit in the number of dimensions and metrics that can be requested
    # information about metrics/dimensions to be used can be found here
    # https://ga-dev-tools.appspot.com/dimensions-metrics-explorer/
    dimensions:
      #identifies user
      - 'ga:date'
      # - 'ga:userType'
      #- 'ga:daysSinceLastSession'
      #- 'ga:sessionCount'
      #- 'ga:country'
      #- 'ga:city'
      # identifies session
      #- 'ga:browserVersion'
      #- 'ga:dateHourMinute'
      #- 'ga:sessionDurationBucket'
      #- 'ga:sourceMedium'
      - 'ga:pagePath'
      #- 'ga:previousPagePath'

      #- 'ga:landingPagePath'
      #- 'ga:exitPagePath'
      #- 'ga:referralPath'
      #- 'ga:city'
      #- 'ga:pagePathLevel1'
      #- 'ga:secondPagePath'
      #- 'ga:sessionDurationBucket'
      #- 'ga:keyword'
      #- 'ga:campaign'
      #- 'ga:fullReferrer'
      #- 'ga:browser'
      #- 'ga:operatingSystem'
      #- 'ga:operatingSystemVersion'
      #- 'ga:mobileDeviceInfo'
      #- 'ga:region'
      #- 'ga:socialNetwork'
      #- 'ga:userBucket'
      #- 'ga:pagePathLevel2'
      #- 'ga:pagePathLevel3'
      #- 'ga:pagePathLevel4'
      #- 'ga:searchKeyword'
      #- 'ga:socialInteractionNetwork'
      #- 'ga:userAgeBracket'
      #- 'ga:interestInMarketCategory'
      #- 'ga:acquisitionCampaign'
    metrics:
      - 'ga:sessions'
      - 'ga:pageviews'
      - 'ga:uniquePageviews'
      # - 'ga:users'
      # - 'ga:sessionDuration'
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/google-analytics/state/{ENV}-processing-state-0.json'
    # Annotations appended to every record created by data pipeline using the config
    # One can use this to differentiate the source data pipeline of a record when several data pipelines
    # write to the same table
    recordAnnotations :
      - recordAnnotationFieldName : 'description'
        recordAnnotationValue: "Does ABC"
    # logResponse: true
  #- pipelineID: '{ENV}'
  #  dataset: '{ENV}'
  #  table: atest_profile_api
  #  viewId: "82618489" # "82626137"
  #  dimensions:
  #    - 'ga:sessions'
  #  metrics:
  #    - 'ga:exitPagePath'
  #  stateFile:
  #    bucketName: '{ENV}-elife-data-pipeline'
  #    objectName: 'airflow-config/google-analytics/state/{ENV}-processing-state-1.json'
  #  recordAnnotations :
   #   - recordAnnotationFieldName : 'name'
   #     recordAnnotationValue: "Senior Editor"
