gcpProjectName: 'elife-data-pipeline'
importedTimestampFieldName: "imported_timestamp"
spreadsheets:
  # sample spreadsheet:
  # https://docs.google.com/spreadsheets/d/1UbM9eExvJligr1bzq22xdK3cL8KIW6oqyJnu8R3uSrU/edit#gid=0
  - spreadsheetId: '1UbM9eExvJligr1bzq22xdK3cL8KIW6oqyJnu8R3uSrU'
    sheets:
      - sheetName: 'Sheet1' # Name of spreadsheet sheet
        sheetRange: 'A:D'
        headerLineIndex: 3
        dataValuesStartLineIndex: 4
        datasetName: "{ENV}"
        tableName: 'test_google_spreadsheet'
        tableWriteAppend: true
        # This adds to every record created by this pipeline config a field whose name is given by metadataSchemaFieldName
        # and whose value is given by the string value of the spreadsheet line given by metadataLineIndex
        inSheetRecordMetadata:
          - metadataSchemaFieldName: 'metadata_example'
            metadataLineIndex: 1

  #    - sheetName: 'Country and continent list'
  #      sheetRange: 'A:B'
  #      tableName: .....
  #      tableWriteAppend: false
  #      headerLineIndex: 0
  #      dataValuesStartLineIndex: 1
  #      datasetName: {ENV}
