projectName: 'elife-data-pipeline'
dataset: '{ENV}'
table: 'crossref_event'
stateFile:
  bucket: 'ci-elife-data-pipeline'
  objectName: 'airflow-config/crossref-event/{ENV}-date-state.json'
schemaFile:
  url:
  bucket: 'ci-elife-data-pipeline'
  objectName: 'airflow-config/crossref-event/data-schema/crossref-event-schema.json'
publisherIdPrefixes:
  - '10.7554'
CrossrefEventBaseUrl: "https://api.eventdata.crossref.org/v1/events?rows=10000"
importedTimestampField: 'data_hub_imported_timestamp'
