projectName: 'elife-data-pipeline'
datasetName: '{ENV}'
surveyMonkeySurveyList:
  table: 'surveymonkey_survey_list'
surveyIdListToRequest:
  - '120828849'  # Reviewer Feedback Opportunity
surveyMonkeySurveyQuestions:
  table: 'surveymonkey_survey_questions'
surveyMonkeySurveyAnswers:
  table: 'surveymonkey_survey_answers'