projectName: 'elife-data-pipeline'
datasetName: '{ENV}'
surveyMonkeySurveyList:
  table: 'surveymonkey_survey_list'
  column: 'id'
surveyMonkeySurveyQuestions:
  table: 'surveymonkey_survey_questions'