projectName: 'elife-data-pipeline'
importedTimestampFieldName: 'imported_timestamp'
webApi:
  - dataset: '{ENV}'
    table: 'testtest_published_research_article'
    datataUrl:
      urlExcludingDynamicParameters: https://observer.elifesciences.org/report/published-research-article-index?format=json
    importedTimestampField: 'data_hub_imported_timestamp'
  - dataset: '{ENV}'
    table: 'testtest_people'
    stateFile:
      bucket: 'ci-elife-data-pipeline'
      objectName: 'airflow-config/crossref-event/{ENV}-processing-state.json'
    schemaFile:
      url:
      bucket: #'ci-elife-data-pipeline'
      objectName: #'airflow-config/crossref-event/data-schema/crossref-event-schema.json'
    datataUrl:
      urlExcludingDynamicParameters: https://api.elifesciences.org/people?per-page=50
      dynamicParameters:
        page: page
    response:
      itemsKeyFromResponseRoot:
        - items

  - dataset: '{ENV}'
    table: 'testtest_people'
    stateFile:
      bucket: 'ci-elife-data-pipeline'
      objectName: 'airflow-config/crossref-event/{ENV}-processing-state.json'
    schemaFile:
      url:
      bucket: 'ci-elife-data-pipeline'
      objectName: 'airflow-config/crossref-event/data-schema/crossref-event-schema.json'
    response:
      itemsKeyFromResponseRoot:
        - a
        - b
      totalItemsCountKeyFromResponseRoot:
        - c
        - d
      nextPageCursorKeyFromResponseRoot:
        - c
        - d
      recordTimestamp:
        timestampFormat: format
        itemTimestampKeyFromItemRoot:
          - e
          - f

    datataUrl:
      urlExcludingDynamicParameters: https://api.elifesciences.org/people?per-page=50
      dynamicParameters:
        page: page
        nextPageCursor: next_page_cursor
        fromDate: from_date
        toDate: to_date
        dateFormat: format
      authentication:
        type: basic
        location:
          authTokenFile: ""
          envVariableHoldingAuthToken: ""
