gcpProjectName: 'elife-data-pipeline'
importedTimestampFieldName: 'data_hub_imported_timestamp'
webApi:
  #observer api
  - dataPipelineId: observer_published_research_article
    description:
      Retrieve legacy POA and VOR publication dates from Observer.
    dataset: '{ENV}'
    table: test_published_research_article
    dataUrl:
      urlExcludingConfigurableParameters: https://observer.elifesciences.org/report/published-research-article-index?format=json
  #elifescience people api
  # - dataset: '{ENV}'
  #   table: test_people_api
  #   dataUrl:
  #     urlExcludingConfigurableParameters: https://api.elifesciences.org/people?
  #     configurableParameters:
  #       pageSizeParameterName: per-page
  #       defaultPageSize: 100
  #       pageParameterName: page
  #   response:
  #     itemsKeyFromResponseRoot:
  #       - items