gcpProjectName: 'elife-data-pipeline'
importedTimestampFieldName: 'data_hub_imported_timestamp'
webApi:
  #- dataset: '{ENV}'
  #  table: 'testtest_people'
  #  the type should only be given when the web api has some very specific implementation requirements
  #  that is not covered by the  generic web api e.g url composition
  #  they web api type name and the type handling functions must be implemented
  #  as of now, the only specific type implemented is 'civi' for handling quirky civicrm rest api
  #  request parameter composition,  information on every other type implemented will be provided here
  #  type: 'civi'
  #  tableWriteAppend: False
  #  stateFile:
  #    bucketName: '{ENV}-elife-data-pipeline'
  #    objectName: 'airflow-config/crossref-event/{ENV}-processing-state.json'
  #  schemaFile:
  #    url:
  #    bucketName: '{ENV}-elife-data-pipeline'
  #    objectName: 'airflow-config/crossref-event/data-schema/crossref-event-schema.json'
  #  Information about how to process the response is provided here
  #  response:
  #    list showing hierarchy (from the response root) of where data values in the json response be found,
  #    for example, consider
  #    response = {'a': {'b': [{}, {}, {}]}}
  #    itemsKeyFromResponseRoot:
  #      - a
  #      - b
  #    list showing hierarchy (from the response root) of where total count of the request response is,
  #    if there is, for example, consider
  #    response = {'a': {'d': 10000000, 'b': [{}, {}, {}]}}
  #    totalItemsCountKeyFromResponseRoot:
  #      - a
  #      - d
  #    list showing hierarchy (from the response root) of where the next page cursor is,
  #    which will be used in composing the next page web api request, for example, consider
  #    response = {'a': {'d': 'XESdErkrsiowE$SREReri', 'b': [{}, {}, {}]}}
  #    nextPageCursorKeyFromResponseRoot:
  #      - a
  #      - d
  #    list showing hierarchy (NOTE from the item/record root) of where the record timestamp is,
  #    response = {'a': {'d': 'XESdErkrsiowE$SREReri', 'b': [{'e':{'f': '2020-01-01'}}, {'e':{'f': '1999-09-13'}}, {}]}}
  #    recordTimestamp:
  #      timestampFormat: '%Y-%m-%d'
  #      itemTimestampKeyFromItemRoot:
  #        - e
  #        - f
  #  dataUrl:
  #    urlExcludingConfigurableParameters: https://api.elifesciences.org/people?per-page=50
  #    configurableParameters:
  #      resultSortParameterName: # request parameter used to hold field used to sort the response
  #      resultSortParameterValue: # field name used to sort the response
  #      pageParameterName: page # request parameter used to specify page number being requested
  #      defaultPageSize: 100
  #      daysDiffFromStartTillEnd: 365 # used in specifying the until date dynamically in the request
  #      offsetParameterName: offset # request parameter used to specify offset number being requested
  #      nextPageCursorParameterName: next_page_cursor # request parameter used to specify cursor of the page being requested
  #      fromDateParameterName: from_date  # request parameter used to specify from date
  #      defaultStartDate:
  #      toDateParameterName: to_date # request parameter used to specify the "until" date
  #      dateFormat: "%Y-%m-%dT%H:%M:%S%z" # how the date format in the request should be formatted as string
  #    parametersFromEnv is used to specify request parameters and values when they values can be
  #    retrieved from the systems environment variable
  #    parametersFromEnv:
  #      - parameterName: api_key # request parameter name
  #        envName: CIVICRM_API_KEY # environment variable holding the value
  #      - parameterName: key
  #        envName: CIVICRM_SITE_KEY
  #    parametersFromFile is used to specify request parameters and values when they values can be
  #    retrieved as files from the system running the data pipeline
  #    parametersFromFile:
  #      - parameterName: api_key  # request parameter name
  #        filePathEnvName: CIVICRM_API_KEY_FILE_PATH  # environment variable holding the location of the file containing the value
  #      - parameterName: key
  #        filePathEnvName: CIVICRM_SITE_KEY_FILE_PATH
  #  authentication configures how the authentication is specified
  #  authentication:
  #    auth_type: basic # simple key-value based authentication, the only implemented so far
  #    orderedAuthenticationParamValues:
  #      TODO: this authentication specs needs to be reworked
  #      how the different values can be retrieved
  #      - value: #
  #        valueFileLocation: #
  #        envVariableHoldingAuthValue: #
  #        envVariableContainingPathToAuthFile: #
  #      specifies how the keys can be retrieved
  #      - paramValue: #
  #        valueFileLocation:
  #        envVariableHoldingAuthValue: #
  #        envVariableContainingPathToAuthFile: #

  #observer api
  - dataset: '{ENV}'
    table: test_published_research_article
    dataUrl:
      urlExcludingConfigurableParameters: https://observer.elifesciences.org/report/published-research-article-index?format=json
  #elifescience people api
  - dataset: '{ENV}'
    table: test_people_api
    dataUrl:
      urlExcludingConfigurableParameters: https://api.elifesciences.org/people?
      configurableParameters:
        pageSizeParameterName: per-page
        defaultPageSize: 100
        pageParameterName: page
    response:
      itemsKeyFromResponseRoot:
        - items
  #elifescience profile api
  - dataset: '{ENV}'
    table: test_people_api
    dataUrl:
      urlExcludingConfigurableParameters: https://api.elifesciences.org/people?
      configurableParameters:
        pageSizeParameterName: per-page
        defaultPageSize: 100
        pageParameterName: page
    response:
      itemsKeyFromResponseRoot:
        - items
  # civi export
  - dataset: '{ENV}'
    table: civi_data_export
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/generic-web-api/{ENV}-civi-export-processing-state.json'
    urlSourceType:
      name: 'civi'
      sourceTypeSpecificValues:
        fieldsToReturn:
          - external_identifier
          - tag
          - group
          - contact_type
          - contact_sub_type
          - last_name
          - first_name
          - middle_name
          - email
          - source
          - user_unique_id
          - organization_name
          - phone
          - city
          - modified_date
    dataUrl:
      urlExcludingConfigurableParameters: https://crm.elifesciences.org/crm/sites/all/modules/civicrm/extern/rest.php?entity=Contact&action=get
      configurableParameters:
        #resultSortParameterName:
        resultSortParameterValue: modified_date
        fromDateParameterName: modified_date
        defaultStartDate: "2012-01-01 00:00:00"
        dateFormat: "%Y-%m-%d %H:%M:%S"
        pageSizeParameterName: limit
        defaultPageSize: 10000
        offsetParameterName: offset
      parametersFromFile:
        - parameterName: api_key
          filePathEnvName: CIVICRM_API_KEY_FILE_PATH
        - parameterName: key
          filePathEnvName: CIVICRM_SITE_KEY_FILE_PATH
    response:
      itemsKeyFromResponseRoot:
        - values
      recordTimestamp:
        itemTimestampKeyFromItemRoot:
          - modified_date

  #hypoothesis api
  - dataset: '{ENV}'
    table: hypothesis_data
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/generic-web-api/{ENV}-hypothesis-processing-state.json'
    dataUrl:
      urlExcludingConfigurableParameters: https://hypothes.is/api/search?group=imRGyeeV&sort=updated&order=asc
      configurableParameters:
        pageSizeParameterName: limit
        defaultPageSize: 100
        fromDateParameterName: search_after
        defaultStartDate: "2012-01-01T01:01:01.000000+00:00"
        dateFormat: "%Y-%m-%dT%H:%M:%S.%f%z"
    response:
      recordTimestamp:
        itemTimestampKeyFromItemRoot:
          - updated
      itemsKeyFromResponseRoot:
        - rows
  #toggle api
  - dataset: '{ENV}'
    table: toggle_data
    stateFile:
      bucketName: '{ENV}-elife-data-pipeline'
      objectName: 'airflow-config/generic-web-api/{ENV}-toggl-processing-state.json'
    dataUrl:
      urlExcludingConfigurableParameters: "https://toggl.com/reports/api/v2/details?workspace_id=3533142&user_agent=api_test&order_field=date&order_desc=off"
      configurableParameters:
        fromDateParameterName: since
        toDateParameterName: until
        defaultStartDate: "2019-07-01"
        dateFormat: "%Y-%m-%d"
        daysDiffFromStartTillEnd: 365
        pageParameterName: page
        defaultPageSize: 50
    response:
      itemsKeyFromResponseRoot:
        - data
      totalItemsCountKeyFromResponseRoot:
        - total_count
      recordTimestamp:
        itemTimestampKeyFromItemRoot:
          - updated
    authentication:
      auth_type: basic
      orderedAuthenticationParamValues:
        - envVariableContainingPathToAuthFile: PATH_TO_TOGGL_API_TOKEN_FILE
        - value: api_token
