projectName: 'elife-data-pipeline'
dataset: 'ci'
#possible values for DEPLOYMENT_ENV_BASED_OBJECT_NAME_MODIFICATION include "replace", "append", "do-not-modify"
#will modifiy the dataset name and data state name
deploymentEnvBasedObjectNameModification: 'replace'
table: 'crossref_event'
stateFile:
  bucket: 'ci-elife-data-pipeline'
  objectName: 'airflow_test/crossref_event/date_state.json'
schemaFile:
  bucket: 'ci-elife-data-pipeline'
  objectName: 'airflow_test/crossref_event/data_schema/crossref_event_schema.json'
publisherIdPrefixes:
  - '10.7554'
CrossrefEventBaseUrl: "https://api.eventdata.crossref.org/v1/events?rows=10000"
messageKey: 'message'
eventKey: 'events'
importedTimestampField: 'data_hub_imported_timestamp'
