projectName: 'elife-data-pipeline'
dataset_name: '{ENV}'
gmailLabelData:
  stageFileName: 'gmail_label_list.json'
  table: 'gmail_label_list'
  stageTable: 'gmail_label_list_staging'
  uniqueIdColumn: 'labelId'
gmailLinkIdsData:
  stageFileName: 'gmail_thread_ids_list.json'
  table: 'gmail_thread_ids_list'
  stageTable: 'gmail_thread_ids_list_staging'
  uniqueIdColumn: 'id'
gmailThreadData:
  stageFileName: 'gmail_thread_details.json'
  table: 'gmail_thread_details'
  listThreadId:
    table: 'gmail_thread_ids_list'
    column: 'threadId'
gmailHistoryData:
  stageFileName: 'gmail_history_details.json'
  table: 'gmail_history_details'
