projectName: 'elife-data-pipeline'
dataset: '{ENV}'
gmailLabelData:
  stageFileName: 'gmail_label_list.json'
  table: 'gmail_label_list'
  stageTable: 'gmail_label_list_staging'
gmailLinkIdsData:
  stageFileName: 'gmail_link_message_thread_ids.json'
  table: 'gmail_link_message_thread_ids'
  stageTable: 'gmail_link_message_thread_ids_staging'
gmailThreadData:
  stageFileName: 'gmail_thread_details.json'
  table: 'gmail_thread_details'
  listThreadId:
    table: 'gmail_link_message_thread_ids'
    column: 'threadId'
gmailHistoryData:
  stageFileName: 'gmail_history_details.json'
  table: 'gmail_history_details'
