projectName: 'elife-data-pipeline'
dataset: '{ENV}'
gmailLabelData:
  stageFileName: 'gmail_label_list.json'
  table: 'gmail_label_list'
gmailLinkIdsData:
  stageFileName: 'gmail_link_message_thread_ids.json'
  table: 'gmail_link_message_thread_ids'
gmailThreadData:
  stageFileName: 'gmail_thread_details.json'
  table: 'gmail_thread_details'
  listThreadId:
    table: 'gmail_link_message_thread_ids'
    column: 'threadId'
