projectName: 'elife-data-pipeline'
datasetName: '{ENV}'
gmailLabelData:
  table: 'gmail_label_list'
  tempTable: 'temp_gmail_label_list'
  uniqueIdColumn: 'labelId'
gmailLinkIdsData:
  table: 'gmail_thread_ids_list'
  tempTable: 'temp_gmail_thread_ids_list'
  uniqueIdColumn: 'id'
gmailThreadData:
  table: 'gmail_thread_details'
  inputColumn: 'threadId'
  historyCheckColumn: 'historyId'
gmailHistoryData:
  tempTable: 'temp_gmail_history_details'
