gcpProjectName: 'elife-data-pipeline'
importedTimestampFieldName: "imported_timestamp"
stateFile:
  defaultBucketName: ci-elife-data-pipeline
  defaultSystemGeneratedObjectPrefix: "airflow-config/{ENV}-s3-csv/state/s3-csv"
s3Csv:
  #- bucketName: elife-ejp-ftp
  #  objectKeyPattern:
  #    - ejp_query_tool_query_id_15a*
  #  dataPipelineId: ejp_query_tool_query_id_15a_unique_id
  #  headerLineIndex: 3
  #  dataValuesStartLineIndex: 4
  #  datasetName: "{ENV}"
  #  tableName: 'ejp_query_tool_query_id_15a_test'
  #  tableWriteAppend: True
  #  stateFile:
  #    bucketName: ci-elife-data-pipeline
  #    objectName: "airflow-config/s3-csv/{ENV}-state/query_id_15a.json"
  #  inSheetRecordMetadata:
  #    - metadataSchemaFieldName: 'date_generated'
  #      metadataLineIndex: 1
  #- bucketName: elife-ejp-ftp
  #  objectKeyPattern:
  #    - ejp_query_tool_query_id_04e*
  #  dataPipelineId: ejp_query_tool_query_id_04e_unique_id
  #  headerLineIndex: 3
  #  dataValuesStartLineIndex: 4
  #  datasetName: "{ENV}"
  #  tableName: 'ejp_query_tool_query_id_04e_test'
  #  tableWriteAppend: True
  #  stateFile:
  #    bucketName: ci-elife-data-pipeline
  #    objectName: "airflow-config/s3-csv/{ENV}-state/query_id_04e.json"
  #  #fixedSheetRecordMetadata :
  #  #  - metadataSchemaFieldName : 'some schema'
  #  #    fixedSheetValue: "Some value"
  #  inSheetRecordMetadata:
  #    - metadataSchemaFieldName: 'date_generated'
  #      metadataLineIndex: 1
  - bucketName: ci-elife-data-pipeline
    objectKeyPattern:
      - airflow_test/test-data/s3_csv_data_pipeline_test_data*
    dataPipelineId: s3_csv_test_data_pipeline
    headerLineIndex: 3
    dataValuesStartLineIndex: 4
    datasetName: "{ENV}"
    tableName: 's3_csv_test_data'
    tableWriteAppend: True
    stateFile:
      bucketName: ci-elife-data-pipeline
      objectName: "airflow_test/state/s3-csv/state.json"
    fixedSheetRecordMetadata :
      - metadataSchemaFieldName : 'metadata_schema_name'
        fixedSheetValue: "metadata_value"
    inSheetRecordMetadata:
      - metadataSchemaFieldName: 'date_generated'
        metadataLineIndex: 1
    recordProcessingSteps: # html
      - html_unescape
